spring:
  redis:
    host: 192.168.153.129
    database: 1
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0
  application:
    name: crowd-management
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/crowd_funding?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: wj1324
    driver-class-name: com.mysql.cj.jdbc.Driver
  #解决spring版本过高swagger不适配的问题
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-circular-references: true

#配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml


server:
  port: 9527

logging:
  level:
    com.wj.crowd.management.mapper: debug
    com.wj.crowd.management.test: debug