spring:
  application:
    name: crowd-pay
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #解决spring版本过高swagger不适配的问题
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 9537


ali:
  pay:
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgpOOmtduYaum1vr0YtRuAxKWaEGmhkKuzyoAEHQ4E3P4JFYJ3seHu9y1YDDSRfysv/x++RkqLIiZm02S0b0/Y49/pcV10ujlZDliHAGsTtcHM+6EeizDAmA5z0dpFNlCoPWhSXOfiaU3PpjPnZX4HEL8M0LSTQytjs90DLncFA8og90I6RVinAQBawu5hCAMTT7Xqh24M08KGbWhytlAuL/5rCppDnQstTO0hORC5Z/5Z29an8IyK0A3EDwMOWziBfqBk/ivdfrsXzZiN6qgeZx8yAMGcpnuMdb6ETb7j20G49ppw8EcOozDaBnzYDxalz3hHU7RTxqiNFGjaWBYJQIDAQAB
    app-id: 2021000119636251
    charset: utf-8
    gateway-url: https://openapi.alipaydev.com/gateway.do
    merchant-private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDSKduhL9yRLRLln+k/4Khz1W9VbsISx9IHkpN2TU7fAQhOOhoB4oUSKZG1q4qaPIhEtvtN6FYMAgM8sTclJATJWkuiGCcTB64eJN2lFJpz0FXDbX2r9T3X+F0BXrdPQy7dWob1DnXndyC36KaYPKKBPBaPpf/FjbjxPpoqpwlB7g9aZK1OMr2Wu+vCWxonQMeB9JjPoOs0d1315eQ1brsGWm1jgWTT4Yvv15irEocBlXduNATYTMoUamrYo+oChzepMqgAE/vnWHLOhrr1TOA7RBl+Wr0+szIc2X3jre5w0Z9e76lAHSjyfMBYzEJ5mR8nQ+b3H1hQvDO7TsO/m+sbAgMBAAECggEATkcc8Op8wu4A7doj7JDm7U4AC9gXHRukFQH5PsUIrXMa/tgRO8Z9PgiRpxLfqxcEwmNNMvVop0xQnFh9a64AwmaJaTSJyULBDaU5kPUdmils6D9t4ZCUmk59hbcbm8AwQm4nejsKm035t8ZF1sou1Ofml1aC77gbvG9OyLgycIVnoDcqiOmtWfue/CTzYdoQDC6Glti/G69CHRG1WU/sbBIuAHhksFFs63InKMgYZTCUNkgBbRz3h/rGZTOSP2LAF2Z50XXbFOMYEIShjZzgfktw+jaRUPcchjCMFRGAxhW3AIWxCYzva40DLfTIj68bjkCnipWgaowpNvtCFzBhgQKBgQD5ZJrqZm+QJIgnhBxgU3koU/Ye3PwBkaEzGCXxWb5UnCDDaNIv6UkY3DIBcVLnUhwZ3zb1CUDxQ40P5Pr3tMpPbapa9oq2bN1a0Xep+zvpIo7xYqeZPD7UuG9u3yQFrAtV6WFZuGq1LG258XzNYUKKi9JtxZMTUfZDryMf4XJTYQKBgQDXuzJVusTPkMYJQN4ZVsumadnIcWHVxKpaTuluz0zrGliZ8pAcDbTbkKrpetIh4oRc1hzMzYguFyCzvUBJdzyr4sf9P70zKNLCX2HlWKNZRKwE6m8qZBFY3nTmX0fsbDEkqqLpqZJvJ3Dtv21B6UC2JyfVEnNh9boW3DzUEE8L+wKBgQDfCXVuWkw9+h32UTVbhGufgG9lrLaH5Kjo3Bja3yrT2omGmVEY3iasYAkstx+wlwNgs/sfa7YzzvjyFRPJwlsIbAhlr4Xgnj3cweamE3TCDFEQWe2PooyCi6vE2TULCZFdtQmGRuLPwrsjB3BY8TmkVGXOHFtrdOqsH45nLaWkIQKBgQCcb97cVAeMDQvOgf+MmGgtUOzgcXfksCxoOHkGJcU9Z2mAmWjvLvFLluiZTrs6Xyxktc9EpHZwFc1dCYuoupKAgn9LogDtLFlJIim3SkOJ5EZpeicKsm3x578Vn1pkk0A/uo1Qq+rIN+2oOfxco2yNqm80D6EkFDDRivuBPCJWKQKBgAXXHEd+gknAOzRrboCN6okbW3a0Dwgn3Xq73ncaqD/PUmaJyVmHAdJmAKNWQzEuko9naARr3XcW2Kva9hjTnDUtMZRFypo7RzWzN8Thxf9jyLWA3qsxtZT+RrsnVZm1qjm2RVQ7X+cgvyndT2NOn024bQpruxrX+mnXMbFU4ax0
    notify-url: http://bzyg39.natappfree.cc/pay/notify #支付回调地址
    return-url: http://locahost/pay/return
    sign-type: RSA2