spring:
  application:
    name: crowd-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: crowd-user
          uri: lb://crowd-user
          predicates:
            - Path=/user/**
        - id: crowd-dynamic
          uri: lb://crowd-dynamic
          predicates:
            - Path=/dynamic/**
        - id: crowd-project
          uri: lb://crowd-project
          predicates:
            - Path=/project/**
        - id: crowd-order
          uri: lb://crowd-order
          predicates:
            - Path=/order/**
        - id: crowd-pay
          uri: lb://crowd-pay
          predicates:
            - Path=/pay/**

server:
  port: 80

