spring:
  application:
    name: crowd-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: crowd-user
          uri: lb://crowd-user
          predicates:
            - Path=/user/**
        - id: crowd-dynamic
          uri: lb://crowd-dynamic
          predicates:
            - Path=/dynamic/**

server:
  port: 80

