spring:
  rabbitmq:
    host: 192.168.153.129
    port: 5672
    username: guest #当前登录的rabbitmq的账号
    password: guest #密码
  application:
    name: crowd-order
  #解决spring版本过高swagger不适配的问题
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.153.129
  session:
    store-type: redis
server:
  port: 9536
