spring:
  application:
    name: crowd-dynamic
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #解决spring版本过高swagger不适配的问题
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  port: 9534